from tkinter import*
from tkinter import messagebox
import mysql.connector
import re
import os
import sys
mis=0
def save(l,m,n,o,p,chk1):
    if(len(l.get())==0 or len(m.get())==0 or len(n.get())==0 or len(o.get())==0 or len(p.get())==0):
        mesagebox.showwarning('NOTE','PLEASE FILL ALL THE FIELDS')
    else:
        if(chk1.get()!=1):
            messagebox.showwarning('INFO','PLEASE AGREE TO THE TERMS AND CONDITIONS')
        else:
            mail=o.get()
            match=re.match('^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$', mail)
            if(match==None):
                messagebox.showwarning('NOTE','PLEASE PROVIDE A VALID EMAIL ADRESS')
                o.delete(0,END)
            elif((len(n.get()))<10):
                messagebox.showwarning('NOTE','PLEASE ENTER A VALID CONTACT NUMBER')
                n.delete(0,END)
            else:
                
                mydb=mysql.connector.connect(host='localhost',user='root',passwd='swaraj1998',database='alinfo')
                crsr=mydb.cursor()
                sql="insert into users(name,town,cntct,email,pwd) values('"+l.get()+"',"+"'"+m.get()+"',"+n.get()+",'"+o.get()+"','"+p.get()+"')"
                sql2="create table "+n.get()+"isuue"+"(name varchar(50),author varchar(20),srlno varchar(5),stock int(100))"
                crsr.execute(sql)
                crsr.execute(sql2)
                mydb.commit()
                messagebox.showinfo('NOTE','SUCCESSFULLY REGISTERED\nPLEASE LOGIN WITH YOUR CONTACT NUMBER AND PASSWORD')
                sql='create table '+n.get()+'table'+'(sub varchar(20),slno varchar(10))'
                crsr.execute(sql)
                mydb.commit()
                l.delete(0,END)
                m.delete(0,END)
                n.delete(0,END)
                o.delete(0,END)
                p.delete(0,END)
def validate(u1,p1):
    if(len(u1.get())==0 or len(p1.get())==0):
        messagebox.showwarning('NOTE','PLEASE ENTER BOTH THE FIELDS')
    else:
        global mis
        mydb=mysql.connector.connect(
        host='localhost',
        user='root',
        passwd='swaraj1998',
        database='alinfo')
        crsr=mydb.cursor()
        sql="select pwd from users where cntct='"+u1.get()+"'"
        crsr.execute(sql)
        d1=p1.get()
        x=crsr.fetchall()
        if(len(x)==0):
            messagebox.showwarning('NOTE','CONTACT DOES NOT EXIST,TRY AGAIN')
            u1.delete(0,END)
        else:
            if(x[0][0]==d1):
                messagebox.showinfo('NOTE','ACCESS GRANTED')
                u1.delete(0,END)
                p1.delete(0,END)
                sys.path.append("C:\\Users\\Swaraj Badhei\\Desktop\\cls python\\prjct\\cmpltd\\resisterbook_project.py")
                w.destroy()
                from resisterbook_project import cse
            else:
                mis+=1
                messagebox.showwarning('NOTE','PLEASE ENTER THE CORRECT PASSWORD')
                p1.delete(0,END)
            if(mis==3):
                messagebox.showwarning('NOTE','ACCESS DENIED')
                u1.delete(0,END)
                p1.delete(0,END)
                w.destroy()
a=555                
def back():
    w=Tk()
    w.geometry('1000x700')
    w.title('Login & Sign up')
    c=Canvas(w,width=4000,height=4000,bg='light green')
    c.place(x=0,y=0)
    p=PhotoImage(file='C:\\Users\\Swaraj Badhei\\Desktop\\cls python\\prjct\\cmpltd\\B1.png')
    p=p.subsample(4,2)
    c.create_image(40,100,image=p,anchor=NW)
    l1=Label(w,text='Login',font=('Lucida Calligraphy',35,'bold'),fg='red',bg='light green')
    l1.place(x=50,y=15)
    l2=Label(w,text='PHONE',font=('times new',20,'bold'),fg='purple',bg='light green')
    l2.place(x=230,y=30)
    e1=Entry(w,bd=5)
    a=e1.get()
    e1.place(x=340,y=35)
    l3=Label(w,text='PASSWORD',font=('times new',20,'bold'),fg='purple',bg='light green')
    l3.place(x=500,y=30)
    e2=Entry(w,bd=5)
    b=e2.get()
    e2.place(x=670,y=35)
    b1=Button(w,text="login",bd=5,bg='gold',command=lambda:validate(e1,e2))
    b1.place(x=850,y=30)
    l4=Label(w,text='Sign Up',font=('Lucida Calligraphy',35,'bold'),fg='red',bg='light green')
    l4.place(x=620,y=80)
    l5=Label(w,text='Name',font=('times new',20,'bold'),fg='purple',bg='light green')
    l5.place(x=500,y=150)
    e3=Entry(w,bd=5,width=36)
    c=e3.get()
    e3.place(x=700,y=155)
    l6=Label(w,text='Address',font=('times new',20,'bold'),fg='purple',bg='light green')
    l6.place(x=500,y=205)
    e4=Entry(w,bd=5,width=36)
    d=e4.get()
    e4.place(x=700,y=210)
    l7=Label(w,text='Gender',font=('times new',20,'bold'),fg='purple',bg='light green')
    l7.place(x=500,y=255)
    r1 = Radiobutton(w,text="Male",value=1,bg='light green')
    r1.place(x=700,y=255)
    r2 =Radiobutton(w,text="Female", value=2,bg='light green')
    r2.place(x=700,y=285)
    l8=Label(w,text='Mobile',font=('times new',20,'bold'),fg='purple',bg='light green')
    l8.place(x=500,y=315)
    e5=Entry(w,bd=5,width=36)
    e=e5.get()
    e5.place(x=700,y=320)
    l9=Label(w,text='Email ID',font=('times new',20,'bold'),fg='purple',bg='light green')
    l9.place(x=500,y=370)
    e6=Entry(w,bd=5,width=36)
    f=e6.get()
    e6.place(x=700,y=375)
    l10=Label(w,text='Password',font=('times new',20,'bold'),fg='purple',bg='light green')
    l10.place(x=500,y=425)
    e7=Entry(w,bd=5,width=36)
    g=e7.get()
    e7.place(x=700,y=430)
    chk=IntVar()
    c1=Checkbutton(w, text = "I agree to all terms and conditions",onvalue = 1, offvalue = 0,variable=chk, height=7,width = 30,bg='light green')
    c1.place(x=650,y=460)
    b2=Button(w,text="Sign Up",bd=5,command=lambda:save(e3,e4,e5,e6,e7,chk))
    b2.place(x=725,y=530)
    w.mainloop()
w=Tk()
w.geometry('1000x700')
w.title('Login & Sign up')
c=Canvas(w,width=4000,height=4000,bg='light green')
c.place(x=0,y=0)
p=PhotoImage(file='C:\\Users\\Swaraj Badhei\\Desktop\\cls python\\prjct\\cmpltd\\B1.png')
p=p.subsample(4,2)
c.create_image(40,100,image=p,anchor=NW)
l1=Label(w,text='Login',font=('Lucida Calligraphy',35,'bold'),fg='red',bg='light green')
l1.place(x=50,y=15)
l2=Label(w,text='PHONE',font=('times new',20,'bold'),fg='purple',bg='light green')
l2.place(x=230,y=30)
e1=Entry(w,bd=5)
a=e1.get()
e1.place(x=340,y=35)
l3=Label(w,text='PASSWORD',font=('times new',20,'bold'),fg='purple',bg='light green')
l3.place(x=500,y=30)
e2=Entry(w,bd=5,show='*')
b=e2.get()
e2.place(x=670,y=35)
b1=Button(w,text="Login",bd=5,bg='light cyan',command=lambda:validate(e1,e2))
b1.place(x=850,y=30)
l4=Label(w,text='Sign Up',font=('Lucida Calligraphy',35,'bold'),fg='red',bg='light green')
l4.place(x=620,y=80)
l5=Label(w,text='Name',font=('times new',20,'bold'),fg='purple',bg='light green')
l5.place(x=500,y=150)
e3=Entry(w,bd=5,width=36)
c=e3.get()
e3.place(x=700,y=155)
l6=Label(w,text='Address',font=('times new',20,'bold'),fg='purple',bg='light green')
l6.place(x=500,y=205)
e4=Entry(w,bd=5,width=36)
d=e4.get()
e4.place(x=700,y=210)
l7=Label(w,text='Gender',font=('times new',20,'bold'),fg='purple',bg='light green')
l7.place(x=500,y=255)
r1 = Radiobutton(w,text="MALE",value=1,bg='light green')
r1.place(x=700,y=255)
r2 =Radiobutton(w,text="FEMALE", value=2,bg='light green')
r2.place(x=700,y=285)
l8=Label(w,text='Mobile',font=('times new',20,'bold'),fg='purple',bg='light green')
l8.place(x=500,y=315)
e5=Entry(w,bd=5,width=36)
e=e5.get()
e5.place(x=700,y=320)
l9=Label(w,text='Email ID',font=('times new',20,'bold'),fg='purple',bg='light green')
l9.place(x=500,y=370)
e6=Entry(w,bd=5,width=36)
f=e6.get()
e6.place(x=700,y=375)
l10=Label(w,text='Password',font=('times new',20,'bold'),fg='purple',bg='light green')
l10.place(x=500,y=425)
e7=Entry(w,bd=5,width=36,show='*')
g=e7.get()
e7.place(x=700,y=430)
chk=IntVar()
c1=Checkbutton(w, text = "I agree to all terms and conditions",onvalue = 1, offvalue = 0,variable=chk, height=7,width = 30,bg='light green')
c1.place(x=650,y=460)
b2=Button(w,text="Sign Up",bd=5,bg='light cyan',command=lambda:save(e3,e4,e5,e6,e7,chk))
b2.place(x=725,y=530)
w.mainloop()
